services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
    networks:
      - homebrewery-network

  homebrewery:
    build:
      context: .
      dockerfile: Dockerfile
    image: homebrewery
    environment:
      MONGODB_URI: mongodb://mongodb/homebrewery
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    networks:
      - homebrewery-network

volumes:
  mongodata:

networks:
  homebrewery-network:
    driver: bridge